In [1]:
# Download MFCCs
!gdown https://drive.google.com/uc?id=1gHWxNPNJ-Yy56gkpdG2ghKfR5r-WvKoV
!unzip -q MFCC-files-v2.zip

Downloading...
From (original): https://drive.google.com/uc?id=1gHWxNPNJ-Yy56gkpdG2ghKfR5r-WvKoV
From (redirected): https://drive.google.com/uc?id=1gHWxNPNJ-Yy56gkpdG2ghKfR5r-WvKoV&confirm=t&uuid=125b03a0-cda1-40d5-842d-70073d7cb997
To: /content/MFCC-files-v2.zip
100% 228M/228M [00:01<00:00, 166MB/s]


In [2]:
# Download Models

# Knn_13_scaled
!gdown https://drive.google.com/uc?id=1OaKxLwxFcJTS1ap9x6nuGMyV2wn8YUfU

Downloading...
From (original): https://drive.google.com/uc?id=1OaKxLwxFcJTS1ap9x6nuGMyV2wn8YUfU
From (redirected): https://drive.google.com/uc?id=1OaKxLwxFcJTS1ap9x6nuGMyV2wn8YUfU&confirm=t&uuid=1420093f-e5bf-4d86-9f63-77cdbd813fab
To: /content/knn_13_scaled.joblib
100% 608M/608M [00:09<00:00, 62.3MB/s]


In [3]:
import pandas as pd
import numpy as np

In [4]:
import joblib
from sklearn.preprocessing import StandardScaler

scaler = joblib.load("knn_13_scaler.joblib")
model = joblib.load("knn_13_scaled.joblib")

In [5]:
columns = list(range(13))

In [ ]:
import os

results = []

for file in os.listdir("MFCC-files-v2"):
  file_name = "MFCC-files-v2/" + file
  test_df = pd.DataFrame(scaler.transform((pd.read_csv(file_name, header=None).T)[columns]), columns=columns)

  predict_proba = model.predict_proba(test_df)

  for proba in predict_proba:
        results.append({"file": file, **{f"prob_class_{i}": proba[i] for i in range(7)}})

  print(file, predict_proba)

results_df = pd.DataFrame(results)


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


98-MFCC.csv [[0.  0.  0.  ... 1.  0.  0. ]
 [0.  0.8 0.  ... 0.  0.2 0. ]
 [0.  0.2 0.  ... 0.  0.8 0. ]
 ...
 [0.  0.2 0.  ... 0.4 0.  0.4]
 [0.  0.2 0.2 ... 0.4 0.  0.2]
 [0.  0.  0.2 ... 0.4 0.  0.4]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


49-MFCC.csv [[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


07-MFCC.csv [[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


13-MFCC.csv [[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


43-MFCC.csv [[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


78-MFCC.csv [[0.  0.  0.  ... 1.  0.  0. ]
 [0.  0.  0.  ... 1.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0.2]
 ...
 [0.  0.  0.  ... 0.  0.  1. ]
 [0.  0.  0.  ... 0.  0.  1. ]
 [0.  0.  0.  ... 1.  0.  0. ]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


60-MFCC.csv [[0.  0.  0.  ... 0.  0.  1. ]
 [0.  0.  0.  ... 0.  0.  1. ]
 [0.  0.  0.  ... 0.8 0.  0.2]
 ...
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


54-MFCC.csv [[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


111-MFCC.csv [[0.  0.4 0.  ... 0.2 0.  0.4]
 [0.  0.6 0.2 ... 0.2 0.  0. ]
 [0.  0.6 0.2 ... 0.2 0.  0. ]
 ...
 [0.  0.6 0.  ... 0.  0.  0.4]
 [0.  0.  0.4 ... 0.4 0.  0.2]
 [0.  0.  0.  ... 1.  0.  0. ]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


27-MFCC.csv [[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


31-MFCC.csv [[0.  0.  0.  ... 0.  0.  1. ]
 [0.  0.  0.  ... 0.  0.  1. ]
 [0.  0.  0.  ... 0.  0.  1. ]
 ...
 [0.  0.  0.6 ... 0.  0.  0.4]
 [0.  0.  0.  ... 0.  0.  1. ]
 [0.  0.  0.  ... 0.  0.  1. ]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


61-MFCC.csv [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


113-MFCC.csv [[0.  0.  0.  ... 0.6 0.  0.4]
 [0.  0.  0.  ... 0.6 0.  0.4]
 [0.  0.  0.  ... 0.6 0.  0.4]
 ...
 [0.  0.  0.  ... 0.6 0.  0.4]
 [0.  0.  0.  ... 0.6 0.  0.4]
 [0.  0.  0.  ... 0.6 0.  0.4]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


40-MFCC.csv [[0.  0.  0.  ... 1.  0.  0. ]
 [0.  0.  0.4 ... 0.6 0.  0. ]
 [0.  0.  0.  ... 0.  0.  1. ]
 ...
 [0.  0.  0.  ... 1.  0.  0. ]
 [0.  0.  0.  ... 1.  0.  0. ]
 [0.  0.  0.  ... 1.  0.  0. ]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


32-MFCC.csv [[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


96-MFCC.csv [[0.  0.  0.6 ... 0.  0.  0.4]
 [0.  0.  0.8 ... 0.2 0.  0. ]
 [0.  0.2 0.8 ... 0.  0.  0. ]
 ...
 [0.  0.2 0.6 ... 0.2 0.  0. ]
 [0.  0.  0.  ... 1.  0.  0. ]
 [0.  0.  0.  ... 0.6 0.  0.4]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [ ]:
results.head()